hypar-io/HyparSpace

ZonePlanningFunctions/SpacePlanningZones/dependencies/SpacePlanningZones.Dependencies.csproj, ZonePlanningFunctions/SpacePlanningZones/hypar.json, ZonePlanningFunctions/SpacePlanningZones/src/SpacePlanningZones.cs, ZonePlanningFunctions/SpacePlanningZones/src/SpacePlanningZones.csproj, ZonePlanningFunctions/SpacePlanningZones/test/SpacePlanningZones.Tests.csproj
per https://www.notion.so/hyparaec/Next-Steps-d4f8e2d055064598bdeed89e50cc9e3a, we would like to make it possible to use the tool without the presence of a Core element. 
- Make `Core` dependency optional
- remove some unnecessary log statements
- Update library versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/hyparspace/2)
=> Make Cores optional for Space Planning Zones

ZonePlanningFunctions/SpacePlanningZones/README.md, ZonePlanningFunctions/SpacePlanningZones/hypar.json, ZonePlanningFunctions/SpacePlanningZones/src/SpacePlanningZones.cs, ZonePlanningFunctions/SpacePlanningZones/src/SpacePlanningZonesInputs.g.cs
- This looks like a huge PR, but it's mostly just lots of refactoring (it's still a bit of a mess)
- enable an option to provide manually drawn circulation instead of automatically drawn
TESTING
- verified that generates reasonable results with manually drawn circulation
- verified that results are unchanged with automatic circulation
COMMENTS
- Won't publish function until https://github.com/hypar-io/Explore/pull/1237 is merged, to ensure new inputs get correct default values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/hyparspace/3)
=> add manual circulation options

ZonePlanningFunctions/Circulation/src/Circulation.cs
@nadiia-volyk noticed that circulation segments were being drawn at the wrong elevation in some scenarios. This is what I found:
- Automatically-generated circulation had the correct elevation
- user-created circulation (via "Add Corridors" override) had: 
- The correct elevation, if drawn while in an active plan view (via the "views" menu)
- the incorrect elevation, if drawn outside of any active focus view. 
When a corridor is drawn outside an active view, it has no `Level` property assigned, and therefore gets drawn on all levels. When this was happening, all created segments were sharing the same `ThickenedPolyline` from the Add override. This is corrected by creating a new ThickenedPolyline for each segment at each level.
Known Issues:
- _deleting_ a CorridorSegment created outside a …
=> Fix circulation polyline when drawn outside of a plan view

ZonePlanningFunctions/Circulation/src/Circulation.cs
Where a circulation segment extends beyond a floor or level boundary, the geometry is trimmed to the boundary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/hyparspace/26)
=> Trim circulation segments to level boundary

LayoutFunctions/MeetingRoomLayout/src/MeetingRoomLayout.cs
missing level volume caused function to error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/34)
=> allow null level volume when getting transform

build-all.sh
github workflow is working well in the pull requests that were recently updated.
We can add fail condition now in case build fails
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/48)
=> build-all.sh: signal error to github workflow if buid failed

LayoutFunctions/Doors/dependencies/Door.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/52)
=> Doors: add 2D visualization by using TryToGraphicsBuffers override

LayoutFunctions/DataHall/.vscode/launch.json, LayoutFunctions/DataHall/.vscode/tasks.json, LayoutFunctions/DataHall/dependencies/DataHallLayout.Dependencies.csproj, LayoutFunctions/DataHall/hypar.json, LayoutFunctions/DataHall/server/DataHallLayout.Server.csproj, LayoutFunctions/DataHall/server/Program.cs, LayoutFunctions/DataHall/src/DataHallLayout.cs, LayoutFunctions/DataHall/src/Function.g.cs
This PR updates the Data Hall Layout function by adding some column avoidance logic. At this stage a rack will simply not be placed where it would intersect with a column. This adds 2 new functions `GetColumnsInRoom` and `CheckIntersectsWithColumn`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/61)
=> Datahall avoid columns

LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs
For Pringle, we need to set the "Space" property on generated furniture. This will also help with future 'per-parent' overrides. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/75)
=> Set parent space on generated furniture

LayoutFunctions/Doors/src/Doors.cs, LayoutFunctions/LayoutFunctionCommon/ISpaceBoundary.cs, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs, LayoutFunctions/PrivateOfficeLayout/dependencies/CirculationSegment.cs, LayoutFunctions/PrivateOfficeLayout/dependencies/LevelVolume.cs
BACKGROUND:
- Circulation spaces were not being included in the `Doors` function.
- We somehow reverted (or forgot?) to using the LevelVolume height instead of the Room height for wall generation.
DESCRIPTION:
- Adds Spaces with `ProgramType` of `Circulation` to the edges to be check for door placement
- Updates the height of walls to be created using the room (`SpaceBoundary`) height instead of the `LevelVolume` height
TESTING:
- See `Doors` respond to the Circulation Space Type
- Review walls beteween multi-story levels
https://hypar.io/workflows/23d33fb9-e90f-427b-b94a-6a12d04a4109?view=Floors%3BLevel%20Group%201%3A%20Level%201
FUTURE WORK:
- Some space types still may need to be updated to reflect these changes... Hoping to move towards a unified `Space Type` function and do away with …
=> Height fix and circulation space for doors

LayoutFunctions/ClassroomLayout/src/ClassroomLayout.cs, LayoutFunctions/DataHall/src/DataHallLayout.cs, LayoutFunctions/LayoutFunctionCommon/LayoutFunctionCommon.csproj, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs, LayoutFunctions/OpenOfficeLayout/Model.dib, LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, LayoutFunctions/OpenOfficeLayout/test/Generated/OpenOfficeLayoutTest/model_dependencies/Space Planning Zones/json/63c2e0df-0d5a-4fd5-a18e-cd7aec794356_998eb115-7d70-49df-9fbe-fbc96a91ae3d_elements.zip, LayoutFunctions/OpenOfficeLayout/test/Generated/OpenOfficeLayoutTest/model_dependencies/Space Planning Zones/json/ddbadd4c-8ebc-4911-af73-5f52ba7a5382_998eb115-7d70-49df-9fbe-fbc96a91ae3d_elements.zip, LayoutFunctions/PhoneBoothLayout/src/PhoneBoothLayout.cs, LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, LayoutFunctions/ReceptionLayout/src/ReceptionLayout.cs
in #75, we added a default behavior to `LayoutFunctionCommon` for associating a `Space` property with elements generated for a space. In this PR, we make sure all non-standard spaces also specify this property. This prepares us for future "per-parent override" type relationships for furniture, and also makes pringle smoother, letting all generated elements travel along with the space without having to do a "containment" check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/78)
=> add space associations for all child elements

LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs
BACKGROUND:
- Configurations could not be rotated, so they were not selected unless they clearly fell within the width and length dimensions of the room
DESCRIPTION:
- This PR adds the ability to rotate the configuration by 90 degrees, if the AllowRotatation field of the configuration is set to "True" (depends on the PR: https://github.com/hypar-io/Elements/pull/1060). This way, the 90 degree rotated version of the configuration will be checked when trying to select it.
TESTING:
- To fill the room with furniture, use the "Space Type" function. When filling the rooms, the version of the configuration rotated by 90 degrees should be taken into account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add rotation to the ContentConfiguration

LayoutFunctions/InteriorPartitions/server/InteriorPartitions.Server.csproj, LayoutFunctions/InteriorPartitions/src/InteriorPartitions.cs
- Update the Interior Partitions function to preserve thickness when it is modified
- This was previously being overriden when removing overlapping walls and splitting. 
- I also updated the wall trim / extension to extend the thicker wall first in corners, which I think looks the least weird
Shared workflow here if you want to see it
https://hypar.io/workflows/5fbc7b87-0102-48ee-86f1-140eff24395e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/80)
=> thickness preservation

LayoutFunctions/ClassroomLayout/hypar.json, LayoutFunctions/ClassroomLayout/src/Function.g.cs, LayoutFunctions/DataHall/hypar.json, LayoutFunctions/DataHall/src/Function.g.cs, LayoutFunctions/InteriorPartitions/src/Function.g.cs, LayoutFunctions/LoungeLayout/hypar.json, LayoutFunctions/LoungeLayout/src/Function.g.cs, LayoutFunctions/MeetingRoomLayout/hypar.json, LayoutFunctions/MeetingRoomLayout/src/Function.g.cs, LayoutFunctions/OpenCollabLayout/hypar.json, LayoutFunctions/OpenCollabLayout/src/Function.g.cs, LayoutFunctions/OpenOfficeLayout/hypar.json, LayoutFunctions/OpenOfficeLayout/src/Function.g.cs, LayoutFunctions/PantryLayout/hypar.json, LayoutFunctions/PantryLayout/src/Function.g.cs, LayoutFunctions/PhoneBoothLayout/hypar.json, LayoutFunctions/PhoneBoothLayout/src/Function.g.cs, LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj, LayoutFunctions/PrivateOfficeLayout/server/PrivateOfficeLayout.Server.csproj, LayoutFunctions/PrivateOfficeLayout/src/Function.g.cs, LayoutFunctions/ReceptionLayout/hypar.json, LayoutFunctions/ReceptionLayout/src/Function.g.cs
Re-publishing functions using the latest Elements and Function versions so that we don't get 404 errors anymore
Tested in this workflow:
https://hypar.io/workflows/95f5e074-2eb7-4c44-8076-b39a78f5ccb8?view=b09eebe9-9857-4fcf-92e4-e4173e928289
I also ran migration tests and saw no issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/84)
=> updates to stream_model before republishing layout functions

LayoutFunctions/ClassroomLayout/src/ClassroomLayout.cs, LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs, LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, LayoutFunctions/PhoneBoothLayout/src/PhoneBoothLayout.cs, LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, LayoutFunctions/ReceptionLayout/src/ReceptionLayout.cs
A small tweak for pringle — stash the space boundary each room was generated from on each object. This lets us restore them to the correct position even if the space has moved since the furniture was generated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/85)
=> set boundary too

LayoutFunctions/ClassroomLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/CustomLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/LayoutFunctionCommon/ISpaceBoundary.cs, LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs, LayoutFunctions/LoungeLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/MeetingRoomLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/OpenCollabLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/OpenOfficeLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/PantryLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/PhoneBoothLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/PrivateOfficeLayout/dependencies/SpaceBoundary.cs, LayoutFunctions/ReceptionLayout/dependencies/SpaceBoundary.cs, SpaceConfigurationFromModel/dependencies/SpaceBoundary.cs
An upcoming pringle PR displays the name (rather than just the dimensions) of layout variants, so a user may select "8P" in a meeting room to get an 8P meeting room. This change revealed some issues:
- because orientation was inconsistent, a different config than the one specified may get chosen.
- because the rooms match the config dimensions *exactly*, we might actually wind up with the next size down. 
This PR creates a pringle-specific pathway based on the existence of the `Config Id` property on a room, which is only set in Pringle. If this property is present:
- We limit the possible configs to the single one matching the config ID
- We force the orientation to use the first edge of the profile segment as its orientation edge
We also add a small amount of tolerance to the "fit" …
=> Limit configs based on `ConfigId` property

LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs
The Pringle-specific code pathway was doing the wrong thing in the case of spaces not at z=0. It was filtering out wall candidate options in 3d, rather than 2d — this resulted in furniture not showing up for spaces not on the ground level.
I pushed this change to all classic layout functions in `test` but have not yet released.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/89)
=> filter wall candidates in 2d

LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs
For some reason, there are two parallel but different versions of `StandardLayoutOnAllLevels` — one that's attached to the `LayoutGeneration` class, and one that lives in `LayoutStrategies`. in #88, we added `LimitConfigsToId` to both of these pathways, but one of them (the one utilized by the `SpaceType` function) generates the `wallCandidateOptions` inside a subsequent method `ProcessRoom`, whereas the "built-in" office space types utilize the other, where `wallCandidateOptions` are available at the moment `LimitConfigsToId` is called.
The functional consequence of this was that built-in types like meeting room had orientation consistency in pringle, but healthcare types generated by `SpaceType` did not.
This PR separates out the logic for forcing a certain orientation into a new method …
=> handle orientation consistency in other pathway

LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs
If edges are all roughly the same length, fall back to the first one to determine orientations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/91)
=> fix: Make orientation for open office consistent

LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs
InteriorPartitions function throws exception for line groups where all items have "Partition" type when
`dominantLineForGroup = linesOrderedByLength.First();` is executed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/92)
=> Use ""Partition" line as dominant is case if all lines are "Partition" to prevent exception

LayoutFunctions/ClassroomLayout/dependencies/ClassroomLayout.Dependencies.csproj, LayoutFunctions/CustomLayout/dependencies/CustomSpaceType.Dependencies.csproj, LayoutFunctions/DataHall/dependencies/DataHallLayout.Dependencies.csproj, LayoutFunctions/Doors/dependencies/Doors.Dependencies.csproj, LayoutFunctions/InteriorPartitions/dependencies/InteriorPartitions.Dependencies.csproj, LayoutFunctions/LayoutFunctionCommon/LayoutFunctionCommon.csproj, LayoutFunctions/LoungeLayout/dependencies/LoungeLayout.Dependencies.csproj, LayoutFunctions/MeetingRoomLayout/dependencies/MeetingRoomLayout.Dependencies.csproj, LayoutFunctions/OpenCollabLayout/dependencies/OpenCollaborationLayout.Dependencies.csproj, LayoutFunctions/OpenOfficeLayout/dependencies/OpenOfficeLayout.Dependencies.csproj, LayoutFunctions/PantryLayout/dependencies/PantryLayout.Dependencies.csproj, LayoutFunctions/PhoneBoothLayout/dependencies/PhoneBoothLayout.Dependencies.csproj, LayoutFunctions/PlantEntourage/dependencies/PlantEntourage.Dependencies.csproj, LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj, LayoutFunctions/ReceptionLayout/dependencies/ReceptionLayout.Dependencies.csproj, SpaceConfigurationFromModel/dependencies/SpaceConfigurationFromModel.Dependencies.csproj, TravelDistanceAnalyzer/dependencies/TravelDistanceAnalyzer.Dependencies.csproj, WorkplaceStrategy/DefineProgramRequirements/dependencies/DefineProgramRequirements.Dependencies.csproj, WorkplaceStrategy/DefineProgramRequirementsMatrix/dependencies/DefineProgramRequirements.Dependencies.csproj, WorkplaceStrategy/WorkplaceMetrics/dependencies/WorkplaceMetrics.Dependencies.csproj
want to bump elements to get the fix for old content element caching that was done in https://github.com/hypar-io/Elements/pull/1080
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/95)
=> bump elemnts

LayoutFunctions/ClassroomLayout/src/ClassroomLayout.cs, LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs, LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs, LayoutFunctions/PhoneBoothLayout/src/PhoneBoothLayout.cs, LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs
After [this change ](https://github.com/hypar-io/Elements/pull/1058) in elements. Revit started deserializing these elements correctly, and then therefore always reporting that layout functions were loading even when there were no actual elements that were valid for loading. This is because we were always adding a InteriorPartitionCandidate element, even when there were no actual partition candidates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/98)
=> don't add a wall candidate element if there are no candidates

LayoutFunctions/WallsLOD200/dependencies/WallsLOD200.Dependencies.csproj, LayoutFunctions/WallsLOD200/src/WallsLOD200.cs
We were allowing walls within a certain distance threshold to be merged if they were collinear, however this made the mergedcollinear method upset because those walls were too far. This PR projects those wall lines that are too far.
Tested against multiple workflows that that threw a WallsLOD200 Hy-ccups:
https://hypar.io/workflows/4c4eb24a-37d6-49e2-bc48-a291462d274f?api=staging
https://hypar.io/workflows/56fd3882-549f-4690-8846-8c8351eb7fa0?api=staging
https://hypar.io/workflows/7304eda5-1718-4c35-a103-52c2ee35263e?api=staging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/100)
=> handle tolerance gaps for WallsLOD200

LayoutFunctions/WallsLOD200/src/WallsLOD200.cs
Evidently using the distance from one line to another was not sufficient to determine if projection was needed. This PR compares the end points of the lines for to determine if they are within tolerance, but further than epsilon, and thus needs projection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/101)
=> check points for distance instead

LayoutFunctions/WallsLOD200/src/WallsLOD200.cs
Sometimes pringle projects only have one level, so we need to support that case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/105)
=> handle 1 level case

LayoutFunctions/WallsLOD200/src/WallsLOD200.cs
It's possible to make lines that are nearly zero length in Pringle, after processing these lines can end up having the same start and end points. This PR removes those nearly zero length lines during our dedup step
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/HyparSpace/106)
=> cull lines shorter than tolerance
